from composants.contact_modal import send_mail as send_mail
from composants.contact_modal import sending_mail as sending_mail
from composants.fichier_afficheur import fichier_afficheur as fichier_afficheur
from composants.langue_select import langue_select as langue_select
from composants.projet_afficheur import projet_afficheur as projet_afficheur
